[project]
name = "bandsalat"
version = "0.1.0"
description = "Bandsalat - A Python project"
requires-python = ">=3.12"
dependencies = [
    "jupyter",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]
